version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
      - image: circleci/mysql:8.0.14
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_DATABASE: myblog
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: docker

    steps:
      - add_ssh_keys:
          fingerprints:
            -"60:c0:95:ec:29:81:14:d4:5c:2f:b7:94:95:8a:18:b0"
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python ./myblog/manage.py test

workflows:
  version: 2
  build_test:
    jobs:
      - build
