version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - add_ssh_keys:
          fingerprints:
            -"60:c0:95:ec:29:81:14:d4:5c:2f:b7:94:95:8a:18:b0"
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            python manage.py test

      # - store_artifacts:
      #     path: test-reports
      #     destination: test-reports
workflows:
  version: 2
  build_test:
    jobs:
      - build
