version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
      - image: circleci/mysql:8.0.14
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_HOST: "127.0.0.1"
          MYSQL_DATABASE: myblog
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: docker
          MYSQL_PASSWORD: docker
    
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            -"60:c0:95:ec:29:81:14:d4:5c:2f:b7:94:95:8a:18:b0"
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: run isort
          command: |
            . venv/bin/activate
            find application/ -name '*.py' -not -path '/home/circleci/repo/venv/*'| isort -ns __init__.py -m 3 -y 

            diff=$(git diff)

            if [[ "${diff}" =~ application/ ]] ; then
              git add .
              git status
              git config --global user.email "developer@ganbaruyo.net"
              git config --global user.name "ganbaruyo Bot"
              git commit -m '[bot] run isort'
              git push origin $CIRCLE_BRANCH
              echo 'done!'
            else
              echo 'nothing to commit!'
            fi
      
      - run:
          name: check codestyle automatically
          command: |
            . venv/bin/activate
            flake8 *.py
            flake8 application/

      - run:
          name: initialize db
          command: |
            . venv/bin/activate
            python application/manage.py makemigrations --settings=myblog.settings.ci
            python application/manage.py migrate --settings=myblog.settings.ci

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python application/manage.py test --settings=myblog.settings.ci

workflows:
  version: 2
  build_test:
    jobs:
      - build
